name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no usuario@IP_DEL_VPS << 'EOF'
            cd /personal/BACK_CRUD_MERN
            git pull origin main  
            npm install           
            pm2 restart crud       
          EOF

